// 从 reference/pindou-color-data 生成 src/data/palettes/*.ts
// 用法：npm run gen:palette
//
// 上游：HansBug/pindou-color-data (MIT License)
//   - mard-221-github/colors.json  MARD 221 色（公开源码库版，主流度 S/5.0）
//   - mard-291-github/colors.json  MARD 291 色（221 + 70 扩展，主流度 S/4.7）
//
// 生成文件只包含原始数据（id/hex/rgb/group），Lab 在运行时由 core/color.ts 计算。

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const REF = resolve(ROOT, 'reference/pindou-color-data')
const OUT_DIR = resolve(ROOT, 'src/data/palettes')

const SOURCE_REPO = 'HansBug/pindou-color-data'
const SOURCE_URL = `https://github.com/${SOURCE_REPO}`
const LICENSE = 'MIT'

/** @param {string} rel @returns {any} */
function readJson(rel) {
  return JSON.parse(readFileSync(resolve(REF, rel), 'utf8'))
}

/** @param {any} color */
function toLine(color) {
  const { code, hex, rgb, group } = color
  if (typeof code !== 'string' || !Array.isArray(rgb) || rgb.length !== 3) {
    throw new Error(`色彩条目格式异常: ${JSON.stringify(color)}`)
  }
  return `  { id: ${JSON.stringify(code)}, hex: ${JSON.stringify(String(hex).toUpperCase())}, rgb: [${rgb.join(', ')}], group: ${JSON.stringify(group)} },`
}

/**
 * @param {object} opts
 * @param {string} opts.file 输出文件名
 * @param {string} opts.varName 导出的变量名
 * @param {string} opts.upstreamId 上游 id（用于注释）
 * @param {any[]} opts.colors
 */
function writePalette({ file, varName, upstreamId, colors }) {
  const banner = [
    '// AUTO-GENERATED by scripts/gen-palette.mjs — DO NOT EDIT BY HAND.',
    `// Source: ${SOURCE_REPO} (${LICENSE}) — ${upstreamId}`,
    `// Upstream: ${SOURCE_URL}`,
    `// Generated: ${new Date().toISOString()}`,
    '',
  ].join('\n')

  const body = `import type { RawPaletteColor } from '../../types'\n\nexport const ${varName}: RawPaletteColor[] = [\n${colors
    .map(toLine)
    .join('\n')}\n]\n`

  writeFileSync(resolve(OUT_DIR, file), `${banner}${body}`)
  return colors.length
}

const mard221 = readJson('mard-221-github/colors.json')
const mard291 = readJson('mard-291-github/colors.json')

if (mard221.colors.length !== mard221.count) {
  throw new Error(`221 colors 数量与 count 不符: ${mard221.colors.length} != ${mard221.count}`)
}
if (mard291.colors.length !== mard291.count) {
  throw new Error(`291 colors 数量与 count 不符: ${mard291.colors.length} != ${mard291.count}`)
}

const n221 = writePalette({
  file: 'mard221.ts',
  varName: 'MARD_221_COLORS',
  upstreamId: mard221.id,
  colors: mard221.colors,
})
const n291 = writePalette({
  file: 'mard291.ts',
  varName: 'MARD_291_COLORS',
  upstreamId: mard291.id,
  colors: mard291.colors,
})

console.log(`✓ MARD 221: ${n221} 色 -> src/data/palettes/mard221.ts`)
console.log(`✓ MARD 291: ${n291} 色 -> src/data/palettes/mard291.ts`)
